name: Go Releaser

on:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  goreleaser:
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.SCHEMACHECK_RELEASE_TOKEN }}

      - name: Attest Provinance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "./dist/schemacheck**"
