# This workflow runs conventional commit checker, semantic release, and goreleaser.

name: Semantic Release

on:
  push:
    branches: [ main ]

jobs:

  test-check-go:
    uses: ./.github/workflows/test-check-go.yaml

  semrelease:

    name: Sem Release
    runs-on: ubuntu-latest
    needs: test-check-go

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.SCHEMACHECK_RELEASE_TOKEN }}
          changelog-generator-opt: "emojis=true"
